/**
 * HomeScreen stories using the real rule engine.
 *
 * Stories with active sessions use the engine adapter to generate
 * realistic session state from dispatched events.
 */
import type { Meta, StoryObj } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { HomeScreen } from './HomeScreen';
import { withProviders, withEngineSession } from '../../../storybook/decorators/providers';
import { withBottomNav } from './storyDecorators';
import { PROGRAM_WITH_TMS, PROGRAM_WITH_CYCLE, SIMPLE_PROGRAM } from '../../../storybook/programs';

const meta: Meta<typeof HomeScreen> = {
	title: 'Screens/HomeScreen',
	component: HomeScreen,
	parameters: {
		layout: 'fullscreen',
	},
	decorators: [withProviders, withBottomNav('home')],
};

export default meta;
type Story = StoryObj<typeof HomeScreen>;

/**
 * Default - the main home screen shown when user
 * has already chosen and loaded a program. Shows program info,
 * next workout, and weekly schedule.
 */
export const Default: Story = {
	args: {
		onNavigate: action('navigate'),
		programMarkdown: PROGRAM_WITH_TMS,
		files: {
			'Fitness/Programs/531.md': PROGRAM_WITH_TMS,
		},
	} as Record<string, unknown>,
};

/**
 * With Cycle Schedule - shows a program using cycle pattern
 * instead of weekly pattern (e.g., Push/Pull/Legs rotation).
 */
export const WithCycleSchedule: Story = {
	args: {
		onNavigate: action('navigate'),
		programMarkdown: PROGRAM_WITH_CYCLE,
		files: {
			'Fitness/Programs/PPL.md': PROGRAM_WITH_CYCLE,
		},
	} as Record<string, unknown>,
};

/**
 * Active Session with Rest Countdown - home screen during
 * an active workout session while resting between sets.
 * The session is generated by the engine with one set completed.
 */
export const WithRestCountdown: Story = {
	args: {
		onNavigate: action('navigate'),
	},
	decorators: [
		withEngineSession('Upper Body', SIMPLE_PROGRAM, {
			'Bench Press': [{ reps: 10, weight: 80, rpe: 7 }],
		}),
		withBottomNav('home'),
	],
};

/**
 * Active Session with Rest Complete - home screen during
 * an active workout session when rest time has elapsed.
 * Shows count-up timer indicating user is ready for next set.
 */
export const WithRestComplete: Story = {
	args: {
		onNavigate: action('navigate'),
	},
	decorators: [
		withEngineSession('Upper Body', SIMPLE_PROGRAM, {
			'Bench Press': [
				{ reps: 10, weight: 80, rpe: 7 },
				{ reps: 10, weight: 80, rpe: 8 },
			],
		}),
		withBottomNav('home'),
	],
};
